name: sweaterweather
description: Weather application.

version: 1.0.4+6

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_dotenv: ^2.1.0
  http: ^0.12.2
  geolocator: ^6.1.13
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  google_fonts: ^1.1.1
  get_it: ^5.0.3
  intl: ^0.16.1
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.2.4
  url_launcher: ^5.7.10
  loader_overlay: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.10

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/country_codes.json
