name: sweaterweather
description: Weather application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_dotenv: ^2.1.0
  http: ^0.12.1
  geolocator: ^5.3.1
  provider: ^4.1.2
  shared_preferences: ^0.5.7+3
  google_fonts: ^1.1.0
  get_it: ^4.0.2
  intl: ^0.16.1
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - country_codes.json
